inherit_gem:
  rubocop-rails:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.4

inherit_from:
  - .rubocop_todo.yml

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Metrics/LineLength:
  Max: 120
  AllowHereDoc: true
  AllowURI: true
