AllCops:
  Exclude:
    - 'db/schema.rb'

inherit_from:
  - .rubocop_todo.yml

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: false
