language: ruby
rvm:
  - 2.4
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rake
  - bundle exec rubocop
notifications:
  slack: rubyforgood:Z8KxX1B7VPwG7MJFRch66746
before_install:
  - curl -fsSL https://get.docker.com/ | sh
  - docker pull ruby
